ftpserver = 'localhost' #adress of FTP server
ftplogin = 'tan' #login for FTP server
ftppassword = 'tan1234' #password for FTP server
pricefile = 'C:\\Users\\WELCOME\\Desktop\\data_to_backup' #path to the FILE
sourceFolder = 'C:\\Users\\WELCOME\\Desktop\\data_to_backup' #path to the FILE
targetFolder = 'C:\\Users\\WELCOME\\Desktop\\data_to_backup_bak' #path to the FILE
archpath = 'C:\\Users\\WELCOME\Desktop\\data_to_backup_bak' #archive FOLDER
ftppath = '/FTP' #path on ftpserver to FOLDER where need upload pfile
sleep = 5 #time to sleep between checks